### ISSUE TITLE
Wrong object id is used

### ISSUE THREAD

**Issue by jornbeyers** [flcdrg/get-azure-app-configuration-action#643]
We have self-hosted runners on VMs and we are using a Service Principal to authenticate and do deployments.
Our GitHub workflow steps look like this:

```yaml
  -   name: Log into Azure
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  -   name: Get Azure App Configuration
      id: get-app-configuration
      uses: flcdrg/get-azure-app-configuration-action@v4
      with:
          resourceGroup: ${{ inputs.RESOURCE_GROUP }}
          appConfigurationName: ${{ inputs.APPCONFIGURATION }}
          keyFilter: '*'
```

From the logs, we get the following error: 

```bash
Run flcdrg/get-azure-app-configuration-action@v4
Error: Caller is not authorized to perform action on resource.
If role assignments, deny assignments or role definitions were changed recently, please observe propagation time.
Caller: appid=xxx;oid=xxx;iss=https://sts.windows.net/xxx/
Action: 'Microsoft.KeyVault/vaults/secrets/getSecret/action'
Resource: '/subscriptions/xxx/resourcegroups/xxx/providers/microsoft.keyvault/vaults/xxx/secrets/apimanagement--subscriptionkey--primary'
Assignment: (not found)
DenyAssignmentId: null
DecisionReason: null 
Vault: xxxx;location=westeurope
```

We can see that it is using the ObjectId of the VM, instead of the ObjectId specified in ${{ secrets.AZURE_CREDENTIALS }}. How can we make sure the service principal details are used?
